#@host = http://localhost:4004
@host = https://433e6c12trial-dev-event-management-system-srv.cfapps.us10-001.hana.ondemand.com

### Get all events ###

GET {{host}}/odata/v4/event/Events
Content-Type: application/json
Accept: application/json

### Get one event ###

GET {{host}}/odata/v4/event/Events(1)
Content-Type: application/json
Accept: application/json

### Create event

POST {{host}}/odata/v4/event/Events
Content-Type: application/json

{
    "ID": "3",
    "name": "Event name"
}

### Update event

PATCH {{host}}/odata/v4/event/Events(3)
Content-Type: application/json

{
    "description": "my description"
}

### Get all participants

GET {{host}}/odata/v4/participant/Participants
Content-Type: application/json
Accept: application/json

###  Get one participant

GET {{host}}/odata/v4/participant/Participants(1)
Content-Type: application/json
Accept: application/json

### Get one participant details

GET {{host}}/odata/v4/participant/Participants(1)/fetchParticipantDetails
Content-Type: application/json
Accept: application/json

### Create participant

POST {{host}}/odata/v4/participant/Participants
Content-Type: application/json

{
    "firstName": "Pepito",
    "lastName": "Perez"
}

### Register participant

POST {{host}}/odata/v4/event/Events(1)/registerParticipant
Content-Type: application/json

{
    "participantId": 1
}

### Get Event participants
GET {{host}}/odata/v4/event/Events(1)/getEventParticipants
Content-Type: application/json

### Cancel event

POST {{host}}/odata/v4/event/Events(1)/cancelEvent
Content-Type: application/json

{
    "cancellationReason": "Tornado"
}

### Reopen event
POST {{host}}/odata/v4/event/Events(1)/reopenEvent
Content-Type: application/json